CREATE OR REPLACE FUNCTION cryo_purge_lt(rel REGCLASS, attname CSTRING, val ANYELEMENT)
RETURNS INT8
AS '$libdir/pg_cryogen.so'
LANGUAGE C STRICT;

CREATE OR REPLACE FUNCTION cryo_purge_le(rel REGCLASS, attname CSTRING, val ANYELEMENT)
RETURNS INT8
AS '$libdir/pg_cryogen.so'
LANGUAGE C STRICT;

CREATE OR REPLACE FUNCTION cryo_purge_gt(rel REGCLASS, attname CSTRING, val ANYELEMENT)
RETURNS INT8
AS '$libdir/pg_cryogen.so'
LANGUAGE C STRICT;

CREATE OR REPLACE FUNCTION cryo_purge_ge(rel REGCLASS, attname CSTRING, val ANYELEMENT)
RETURNS INT8
AS '$libdir/pg_cryogen.so'
LANGUAGE C STRICT;
